---
kind: ImageStreamList
apiVersion: v1
metadata: {}
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: sx-dbtools
      annotations:
        openshift.io/display-name: sx-dbtools
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: sx-dbtools (latest)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: ImageStreamTag
            name: stable
        - name: devel
          annotations:
            openshift.io/display-name: sx-dbtools (devel)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: DockerImage
            name: startx/db-tools:latest
        - name: stable
          annotations:
            openshift.io/display-name: sx-dbtools (stable)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            version: stable
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: DockerImage
            name: startx/db-tools:stable
        - name: 0.1.40
          annotations:
            openshift.io/display-name: sx-dbtools (v0.1.40)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            version: stable
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: DockerImage
            name: startx/db-tools:0.1.40
        - name: 0.1.21
          annotations:
            openshift.io/display-name: sx-dbtools (v0.1.21)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            version: stable
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: DockerImage
            name: startx/db-tools:0.1.21
        - name: 0.1.15
          annotations:
            openshift.io/display-name: sx-dbtools (v0.1.15)
            description:
              Database tools for manipulating couchbase and mariadb container.
              For more information about using this builder image, including OpenShift
              considerations, see https://github.com/startxfr/docker-db-tools-example.git
            iconClass: icon-mysql-database
            tags: database,mysql,couchbase
            supports: mysql,couchbase
            version: stable
            sampleRepo: https://github.com/startxfr/docker-db-tools-example.git
          from:
            kind: DockerImage
            name: startx/db-tools:0.1.15
