apiVersion: v1
kind: Template
metadata:
  name: startx-dbtools
  annotations:
    description: Container for managing data from a mysql and/or a couchbase backend
    iconClass: icon-play
    tags: database,couchbase,mariadb
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: "${DBTOOLS_NAME}"
  data:
    COUCHBASE_ADMIN: "${COUCHBASE_ADMIN}"
    COUCHBASE_PASSWORD: "${COUCHBASE_PASSWORD}"
    COUCHBASE_BUCKET: "${COUCHBASE_BUCKET}"
- kind: StatefulSet
  apiVersion: apps/v1beta1
  metadata:
    name: "${DBTOOLS_NAME}"
  spec:
    serviceName: "${DBTOOLS_NAME}"
    template:
      metadata:
        labels:
          name: "${DBTOOLS_NAME}"
          app: dbtools
          type: tools
        annotations:
          pod.alpha.kubernetes.io/initialized: 'true'
          scheduler.alpha.kubernetes.io/affinity: "{}"
      spec:
        terminationGracePeriodSeconds: 86400
        containers:
        - name: dbtools
          image: "${REGISTRY}:${IMAGE_NAME}"
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /bin/startx_dbtools
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
          - name: COUCHBASE_ADMIN
            value: "${COUCHBASE_ADMIN}"
          - name: COUCHBASE_PASSWORD
            value: "${COUCHBASE_PASSWORD}"
          lifecycle:
            preStop:
              exec:
                command:
                - "/bin/startx_dbtools"
                - debug
          resources:
            requests:
              memory: "${MEMORY_LIMIT_DATA}"
              cpu: 0.1
            limits:
              memory: "${MEMORY_LIMIT_DATA}"
          volumeMounts:
          - mountPath: "/data"
            name: data
    volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: "${STORAGE_CLASS_DATA}"
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "${VOLUME_CAPACITY_DATA}"
parameters:
- name: DBTOOLS_NAME
  displayName: Application Name
  description: The name of the Application exposed.
  value: dbtools
  required: true
- name: COUCHBASE_ADMIN
  displayName: Couchbase Connection Username
  description: Username for Couchbase user that will be used for accessing the database.
  generate: expression
  from: user[A-Z0-9]{3}
  required: true
- name: COUCHBASE_PASSWORD
  displayName: Couchbase Connection Password
  description: Password for the Couchbase connection user.
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: COUCHBASE_BUCKET
  displayName: Couchbase Bucket Name
  description: Name of the Couchbase database accessed.
  value: bucket
  required: true
- name: IMAGE_NAME
  value: latest
  required: true
- name: REGISTRY
  value: "startx/db-tools"
  required: true
- name: MEMORY_LIMIT_DATA
  displayName: Memory Limit for data nodes
  description: Maximum amount of memory data container can use.
  value: 1Gi
- name: VOLUME_CAPACITY_DATA
  displayName: Volume Capacity for data nodes
  description: Volume space available for data nodes, e.g. 512Mi, 2Gi.
  value: 512Mi
  required: true
- name: STORAGE_CLASS_DATA
  displayName: Storage Class for data nodes
  description: Storage Class of the volume space for data nodes, e.g. fast, slow
  value: slow
  required: true
labels:
  template: startx-dbtools-template