app:
  image: startx/db-tools:latest
  environment:
   - MYSQL_HOST=mydb.mydomain.com
   - MYSQL_DATABASE=demo,demo2,demo3
   - MYSQL_ADMIN=root:rootPassword
   - MYSQL_USERS=demo:pwd,user3:pwd3,test
   - COUCHBASE_HOST=cluster.couchbase.mydomain.com
   - COUCHBASE_ADMIN=demo:password
   - COUCHBASE_BUCKET=demo,demo2
   - COUCHBASE_USERS=demo1:password1,demo2
  command: ["create"]