app:
  image: startx/db-tools:latest
  links:
    - db-mysql:dbm
  environment:
   - MYSQL_DATABASE=demo,demo2,demo3
   - MYSQL_ADMIN=root:rootPassword
   - MYSQL_USERS=demo:pwd,user3:pwd3,test
  command: ["create" , "mysql"]

db-mysql:
  image: mariadb:10.0
  container_name: "sx-dbtools_mysql"
  environment:
   - MYSQL_ROOT_PASSWORD=rootPassword

pma:
  image: phpmyadmin/phpmyadmin
  container_name: "sx-dbtools_pma"
  links:
    - db-mysql:db
  environment:
   - PMA_HOST=db
   - PMA_USER=root
   - PMA_PASSWORD=rootPassword
   - PMA_ABSOLUTE_URI=http://localhost:1901
  ports:
    - "1901:80"